### ISSUE TITLE
Different crawl speed

### ISSUE THREAD

**Issue by PeterL328** [PeterL328/SnakeRobot#1]
we need to find to update the crawl speed based on the diffrerent stick values not just 
if (leftStick > 0). We need to map the stick values to the speed and we also need to find what changes the snakes crawl speed. Is it the period? amplitude? ...

**Comment by PeterL328** [comment]
It looks like we can modify the Ardusnake library by adding some delay inside the function "void Oscillator::refresh()". By doing that i think we can introduce speed into the oscillation.

**Comment by michaellzc** [comment]
你是指修改摆动的刷新率？来改变速度

Date: Thu, 21 Aug 2014 09:13:03 -0700

**Comment by PeterL328** [comment]
我如果想要让robot爬慢点的话，需要修改这个function。在library里面。
void Oscillator::refresh（这里加个什么速度的输入)
{

  //-- Only When TS milliseconds have passed, the new sample is obtained
  if (next_sample()) {

```
  //-- If the oscillator is not stopped, calculate the servo position
  if (!_stop) {
    //-- Sample the sine function and set the servo pos
    _pos = round(_A * sin(_phase + _phase0) + _O);
if (_rev) _pos=-_pos;
    _servo.write(_pos+90);
    // 这里根据speed input 来决定该delay多少
     //比如说 delay（100）可能就慢了30%
    //-- Increment the phase
    _phase = _phase + _inc;
  }  
```

  }

**Comment by michaellzc** [comment]
那这个的修改要等到回学校才能做吧

**Comment by michaellzc** [comment]
另外你赶快去搞个skybe吧，这样电脑开着就能方便联系了，手机经常看不到

**Comment by PeterL328** [comment]
Ok 这个问题解决了。 我们该period就可以了。 还记得sine吗

**Comment by PeterL328** [comment]
我改了下period， 趴的还挺快的
