### ISSUE TITLE
I2C handskake

### ISSUE THREAD

**Issue by PeterL328** [PeterL328/SnakeRobot#2]
We need to find a way to verify if the slaves have successfully received some data, otherwise we are talking blindly.

**Comment by michaellzc** [comment]
这个我试试吧

**Comment by michaellzc** [comment]
详细点：是指确认成功收到ps2手柄的指令么

**Comment by PeterL328** [comment]
对呀，有些时候我发的东西另外一遍收不到。

**Comment by PeterL328** [comment]
如果少收到个东西比如说 'S' 后面收到的都打乱了。还有个 我发现 我们不能
同时发全部的ps2 stick的值。

Wire.begintransmission(...)
Wire.send('S');
Wire.send(leftY);
Wire.send(leftX);
Wire.send(rightY);
Wire.send(rightX);
Wire.endtransmission();

我们要吗把它分开
Wire.begintransmission(...)
Wire.send('S');
Wire.send(leftY);
Wire.endtransmission();

Wire.begintransmission(...)
Wire.send('D');
Wire.send(leftX);
Wire.endtransmission();

Wire.begintransmission(...)
Wire.send('F');
Wire.send(rightY);
Wire.endtransmission();

Wire.begintransmission(...)
Wire.send('G');
Wire.send(rightX);
Wire.endtransmission();

**Comment by michaellzc** [comment]
原因呢？数据上行的带宽限制？

**Comment by PeterL328** [comment]
Ok, too many mistakes with I2C. We will just use one arduino.
I bought some sensors(gyroscopes), maybe we can use I2C with that...
