### ISSUE TITLE
Not moving to the right place

### ISSUE THREAD

**Issue by PeterL328** [PeterL328/SnakeRobot#5]
When i move the left stick to the southeast or southwest direction, it moves to the opposite direction. 
Also when i move to the south direction the robot doesn't come to me,it moves foward...
The rest is fine, just these.

**Comment by michaellzc** [comment]
代码的问题么。。。步法错了？

**Comment by PeterL328** [comment]
可能是就是步法吧。很奇怪的事他往
左右动是没问题，就是不往反着走。

**Comment by michaellzc** [comment]
回去一起再测试吧

--- Original Message ---

**Comment by michaellzc** [comment]
Add initial value to global variable lefts and lefty
