### ISSUE TITLE
Need ideas for buttons

### ISSUE THREAD

**Issue by PeterL328** [PeterL328/SnakeRobot#6]
We have many buttons left. We need to think of what to use them for. Any ideas?

**Comment by michaellzc** [comment]
比如我们设计些固定的动作，按一下就可以表现出来

**Comment by PeterL328** [comment]
The one -> http://youtu.be/oA81eWMACgM

**Comment by PeterL328** [comment]
The one (0:49-1:00) camera mode- > http://youtu.be/T62E-_pQt3c

**Comment by PeterL328** [comment]
http://youtu.be/8jvwrvbYAiY

**Comment by michaellzc** [comment]
嗯
